# General  
finetune: False
partial_train: null

# Training 
epochs: 300
batch_size: 2
lr_backbone: 0.0001
lr_head: 0.0001
weight_decay: 0.01
lr_decay: 0.99

# Model
model_version: class
maxlen: 243
dim_feat: 512
mlp_ratio: 2
depth: 5
dim_rep: 512
num_heads: 8
att_fuse: True
num_joints: 17
hidden_dim: 2048
dropout_ratio: 0.5

# Data
dataset: custom
data_split: custom
clip_len: 243
action_classes: 52  # Number of classes detected from your data
data_root: data  # Path to data directory

# Augmentation
random_move: True
scale_range_train: [1, 3]
scale_range_test: [2, 2]
normalize: True  # Apply pose normalization

# Custom dataset specific settings
preprocess_3d: True  # Indicates working with 3D pose data directly
skip_2d_lifting: True  # Skip 2D-to-3D lifting pretraining stage 