# General  
finetune: False
partial_train: null

# Training 
epochs: 300
batch_size: 24
lr_backbone: 0.00001
lr_head: 0.00008
weight_decay: 0.1
lr_decay: 0.98

# Model
model_version: class
maxlen: 243
dim_feat: 192
mlp_ratio: 2
depth: 2
dim_rep: 96
num_heads: 4
att_fuse: True
num_joints: 17
hidden_dim: 64
dropout_ratio: 0.7

# Data
dataset: custom
data_split: custom
clip_len: 243
action_classes: 52  # Number of classes detected from your data
data_root: data  # Path to data directory

# Augmentation
random_move: True
scale_range_train: [0.8, 3.2]
scale_range_test: [2, 2]
normalize: True  # Apply pose normalization

# Custom dataset specific settings
preprocess_3d: True  # Indicates working with 3D pose data directly
skip_2d_lifting: True  # Skip 2D-to-3D lifting pretraining stage 